env: local
addr: 0.0.0.0:8187

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  logs_queue: monitor_logs
  robot_queue: monitor_robot
  binding_log_key: quantized-monitor_log
  binding_robot_key: quantized-monitor_robot
  exchange: quantized
  exchange_type: direct